version: "3.8"
services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=/
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    #volumes:
    #  - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.config
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  celery_worker:
    build:
      context: .
    environment:
      - CELERY_BROKER=amqp://admin:admin@rabbitmq:5672//
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: python -m celery -A core.celery worker --loglevel=info
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure

  celery_beat:
    container_name: celery_beat
    build:
      context: .
    command: python -m celery -A core.celery beat --loglevel=info
    depends_on:
      - celery_worker
